service: pdf-thumbnail

custom:
  bucketName: dev-mycrm-thumbnail

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: aws-apikey-dev
  memorySize: 128
  timeout: 300
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::${self:custom.bucketName}/*
        - arn:aws:s3:::${self:custom.bucketName}

package:
  include:
    - node_modules/*

functions:
  thumbnail:
    handler: thumbnail.handler
    events:
      - http:
          method: get
          path: thumbnail
          cors:
            origin: '*'
