service: pdf-thumbnail

custom:
  bucketName: dev-mycrm-thumbnail

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: aws-apikey-dev
  memorySize: 1024
  timeout: 300
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::${self:custom.bucketName}/*
        - arn:aws:s3:::${self:custom.bucketName}

functions:
  thumbnail:
    handler: thumbnail.handler
    layers:
      - arn:aws:lambda:ap-southeast-2:001256626925:layer:image-magick:1
      - arn:aws:lambda:ap-southeast-2:175033217214:layer:graphicsmagick:2
      - arn:aws:lambda:ap-southeast-2:764866452798:layer:ghostscript:8
    events:
      - http:
          method: get
          path: thumbnail
          cors:
            origin: '*'
